; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=otf | FileCheck %s

define void @simple(i11 %x) {
; CHECK-LABEL: simple:
; CHECK:       # %bb.0:
; CHECK-NEXT:  	CALL 1 __set_0
; CHECK-NEXT:  	CALL 0 __del_1
  ret void
}
