; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=otf | FileCheck %s

define i8 @simple(i8 %x) {
; CHECK-LABEL: simple:
; CHECK:       # %bb.0:
  ret i8 %x
}

define i8 @simple2(i8 %x) {
; CHECK-LABEL: simple2:
; CHECK:       # %bb.0:
; CHECK-NEXT:  	CALL 1 __set_0
; CHECK-NEXT:  	CALL 0 __del_1
; CHECK-NEXT:  	CALL 0 __push_0
  ret i8 0
}

define i8 @increment(i8 %x) {
; CHECK-LABEL: increment:
; CHECK:       # %bb.0:
; CHECK-NEXT:  	CALL 1 __add_1
; CHECK-NEXT:  	CALL 1 __unset_magic
    %ret = add i8 %x, 1
    ret i8 %ret
}
